#!/usr/bin/env bash
# 3-redirection
# Configures Nginx to redirect /redirect_me (301 Moved Permanently)

# Exit immediately if a command fails
set -e

# Update & install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Backup default configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Overwrite default config with redirect included
sudo cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

